### ISSUE TITLE
replace `re.sub`s with `re.compile`s for speed

### ISSUE THREAD

**Issue by naveen-marthala** [carpedm20/emoji#187]
replace `re.sub`s with `a_variable = re.compile`s, then do `a_variable.sub()` for speed.

**Comment by cvzi** [comment]
Looks like it is only used in https://github.com/carpedm20/emoji/blob/57f010aa5776672c390796443a24cdc1e6d33726/emoji/core.py#L102 and 
https://github.com/carpedm20/emoji/blob/57f010aa5776672c390796443a24cdc1e6d33726/emoji/core.py#L108
Since the argument `u'\ufe0f'` does not contain any regexp symbols, it should be even faster to use `str.replace(oldstr,newstr)` 
```python
get_emoji_regexp(language).sub(replace, string).replace(u'\ufe0f', '')
``` 

Altough I am not sure if this is still correct. We might have to remove `u'\ufe0f` (emoji type variant) and `u'\ufe0e` (text type variant), I will investigate that. 
But str.replace() twice is probably still faster than using one regular expression sub()
```python 
get_emoji_regexp(language).sub(replace, string).replace(u'\ufe0e', '').replace(u'\ufe0f', '')
```
