### ISSUE TITLE
emoji match

### ISSUE THREAD

**Issue by Alone749-i** [carpedm20/emoji#198]
Hello, I was busy some time ago and did not reply to your email in time.
My English is not very good, so I translated it from Chinese to English. There may be some grammatical problems. I hope you can understand.
In the function get_emoji_regexp(), the regular expression matching emoji is not very suitable.
You are sorting the emoji list to prevent splitting the combined emojis during matching, but such regular expression matching speed can be said to be very slow. I have rewritten an emoji matching function myself, hoping to replace the original The matching function. The speed is about 9 to 10 times that of the old matching speed, and the accuracy is the sam
[emoji_re.txt](https://github.com/carpedm20/emoji/files/7674642/emoji_re.txt)
e.

**Comment by cvzi** [comment]
In the next version [v1.6.2](/carpedm20/emoji/releases/tag/v1.6.2) the regular expression is not used. I have replaced it with a search in a search tree:
Search tree: [emoji/core.py#L347-L407](/carpedm20/emoji/blob/e35fc45168376b273d8d04630dbb7f46c4544989/emoji/core.py#L347-L407)
New demojize(): [emoji/core.py#L173-L218](/carpedm20/emoji/blob/e35fc45168376b273d8d04630dbb7f46c4544989/emoji/core.py#L173-L218)

The `emoji_lis()` function also uses `demojize()` instead of the regular expression, so it should be faster now as well.
