### ISSUE TITLE
Persian/Farsi Lanuage emoji support

### ISSUE THREAD

**Issue by AliNajafi1998** [carpedm20/emoji#225]
Hi, 
I wanted to know if you want to support persian language or not?
if yes, I would like to work on it.

**Comment by cvzi** [comment]
I have checked Arabic and there were some problems with the diacritics (NFC vs. NFD form) that would need to be solved. I think similar problem will happen with Persian. 

You can try it by adding a new line with 'fa' here:
https://github.com/carpedm20/emoji/blob/c398e0c5ff6ceff08c7860078b242765f093f285/utils/get_codes_from_unicode_emoji_data_files.py#L210-L215

That will download the translations and write the new dict to `out.py`:
```sh
python utils/get_codes_from_unicode_emoji_data_files.py > out.py
```
Copy the content from `out.py` into the EMOJI_DATA dict in `emoji/unicode_codes/data_dict.py`

Then you can run the tests:
```sh
pytest

```

**Comment by AliNajafi1998** [comment]
Great!

I will look at NFC and NFD forms as well, btw if you have some examples for those I would like to look at them.

**Comment by cvzi** [comment]
The problem is that for example alef with hamza in unicode can be either a single character or two characters.
It can be alef character followed by hamza character (NFD - normalized form **D**ecomposed) or it can be one combined character (NFC - normalized form **C**omposed):
 أ `\u0627\u0654` 
 أ `\u623`

Currently we can only detect an emoji name (`:name_with_alefhamza_أ:`) with the single-character form NFC. We cannot detect an emoji name that contains the two-character NFD form.
This is because the regular expression group `\w` does not include the two-character form and we use that to find the `:emoji_name:`
https://github.com/carpedm20/emoji/blob/c398e0c5ff6ceff08c7860078b242765f093f285/emoji/core.py#L81-L82


This also happens in other languages, for example in German and Turkish there is ö which can be either `\u00f6` or `o \u0308`.
However German and Turkish keyboards already have the ö character on them and these keyboards always use the single-character form. So the two-character form is not really used anywhere and it is not a big problem.

But Arabic doesn't have a keyboard with all the letters with diacritics, so sometimes a text will have the single-character form and sometimes it will have the two-character form. Therefore in Arabic this would be a problem.

I think a solution could be to add all the diacritics like hamza to that regular expression, but I have not checked it yet
https://github.com/carpedm20/emoji/blob/c398e0c5ff6ceff08c7860078b242765f093f285/emoji/core.py#L81-L82

**Comment by AliNajafi1998** [comment]
Got it!
I will try to resolve this issure for Arabic after checking Persian.

**Comment by AliNajafi1998** [comment]
Regarding ```hamza``` in Persian/Farsi. Actually, the Persian language has only 32 alphabets that you can check them here: [wikipedia](https://fa.wikipedia.org/wiki/%D8%A7%D9%84%D9%81%D8%A8%D8%A7%DB%8C_%D9%81%D8%A7%D8%B1%D8%B3%DB%8C). 

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Persian_alphabet.gif/300px-Persian_alphabet.gif)

However, because Farsi and Arabic have lots of common words, sometimes even in Farsi they are using ```hamza``` . 

Some examples: 
   - without hamza: ```دکمه بزرگ```
   - with hamza:  ```دکمهٔ بزرگ```
   - also sometimes we write like this using ```\u200c``` :  ```دکمه‌ی بزرگ```              
Meaning: The Big button


So what I have in my mind is we can remove hamza for Farsi and replace them with normals style.

Therefore the problems for Farsi will be resolved.

**Comment by AliNajafi1998** [comment]
Even if you look at the written style of 🅿️ in [empji list](https://emojiterra.com/copypaste/fa/). There is no ```hamza```! :D

**Comment by cvzi** [comment]
So it still feels natural to read without the hamza? It is not a problem to remove it? Does a Persian keyboard even have hamza on it?

(Because we don't have to remove it, I am sure I could solve it another way. I'll need to solve it anyway in the future if I want to add Arabic)

I can see 🅿️ is `دکمه پی` but 🆒 is with hamza `دکمهٔ COOL` ??
The hamza also appears in all the "japanese" buttons e.g. 🈷️​🈶​🈂️​🈁​🈯​ as به ژاپنی 
E.g. `دکمۀ «رایگان» به ژاپنی` would turn into  `دکم «رایگان» ب ژاپنی`

---

I don't know if you saw, this is the actual source file: https://github.com/unicode-org/cldr/blob/release-41/common/annotations/fa.xml
emojiterra.com is a bit outdated, they have not updated their website yet. emojiterra.com uses the values with the `type="tts"` so we use these as well.

**Comment by AliNajafi1998** [comment]
Yes, without hamza nothing gets changed. in Persian keyboard, yes it is available but people normally don't use it.
But I understand your concern about solving it without removing it.

yes, in buttons sometimes they are with hamza, and sometimes they are not, and there is no difference while reading it.

For Japanese buttons, I can see the RTL problem :/

**Comment by cvzi** [comment]
Ok, I agree, let's remove hamza in Farsi. 

I think the RTL problem is just because I used the github markdown code. I put it in a sentence in google translator and it seems ok:

> یک :دکمه_cool: و :دکمه_«تبریک»_به_ژاپنی: وجود دارد

**Comment by cvzi** [comment]
I see another thing with the "Japanese buttons", they have quotations marks « and »:
```python
u'\U0001F237\U0000FE0F': { # 🈷️
        'en' : ':Japanese_monthly_amount_button:',
        'de': u':schriftzeichen_für_monatsbetrag:',
        'es': u':ideograma_japonés_para_cantidad_mensual:',
        'fr': ':bouton_montant_mensuel_en_japonais:',
        'pt': u':botão_japonês_de_“quantidade_mensal”:',
        'it': u':ideogramma_giapponese_di_“importo_mensile”:'
    },
```
Farsi would be: `:دکمه_«مقدار_ماهانه»_به_ژاپنی:` or `:دکمه_مقدار_ماهانه_به_ژاپنی:`

You have to decide if you want to remove the quotation marks in Farsi or keep them.

**Comment by AliNajafi1998** [comment]
I added Persian language and made a PR.
