### ISSUE TITLE
Missing catholic symbols

### ISSUE THREAD

**Issue by novitae** [carpedm20/emoji#253]
Hello, I just noticed the following catholic (or roman) symbols are missing:
```
✞
✟
☨
♰
♱
☩
☧
```
There's probably a lot more of the same type (not pretty colored and displayed) missing, do you plan to implement them ? Thanks

**Comment by cvzi** [comment]
They are not considered emoji by Unicode.org, therefore they will not be included in this package. 

If you need a few extra symbols, you can just make a copy of the repository and add the symbols you need to EMOJI_DATA dict in https://raw.githubusercontent.com/carpedm20/emoji/master/emoji/unicode_codes/data_dict.py (3 MB)

Example to use ✞ as `:my_shadowed_cross:`

```python
    u'✞': {
        'en' : ':my_shadowed_cross:',
        'status' : fully_qualified,
        'E' : 0.5,
    },
```

---

I had previously thought about making an extension package with the non-emoji symbols.
I abandoned that idea, because there a lot of symbols, and it is unclear which should be included and which are widely supported.

There is an overview of all (?) unicode symbols at https://www.amp-what.com/blocks.html and https://unicodes.jessetane.com/

**Comment by novitae** [comment]
Alright now I understand, thanks

> I had previously thought about making an extension package with the non-emoji symbols. I abandoned that idea, because there a lot of symbols, and it is unclear which should be included and which are widely supported.

I figured out macOS have a very large library of emojis, with some details associated to each (see linked the image). Maybe it could be made easily by finding out where all these data are stored and translate them in json ? And for the one supported, if the goal is to reference all the possible ones, then you can't reference only the widely supported ones ...
<img width="1250" alt="Capture d’écran 2023-03-15 à 13 15 32" src="https://user-images.githubusercontent.com/85891169/225306239-edce9c70-8a6f-4494-bb0d-ad41c953ad1f.png">

**Comment by cvzi** [comment]
Thanks, that's interesting, I didn't know this tool.

I'll add some more information, in case I or someone else ever decides to work on this:

I would not want to reference all of them. I would only be interested in the ones that are widely supported, that is Apple, Android and Windows. 
The other problem I faced were "symbols" that are actually letters of a language. They might look like random symbols to someone who doesn't know that language. For example some people use `ツ` or `ㇱ` instead of `:)`, but those are Japanese letters not "symbols". Including them might be good for Western users, but would be problematic for Japanese users.

Here some more Python related info:

You can get the "name" of any symbol in Python like this:
```python
>> print('✞'.encode('ascii', 'namereplace').decode('ascii'))
\N{SHADOWED WHITE LATIN CROSS}

>> print('🨞'.encode('ascii', 'namereplace').decode('ascii'))
\N{WHITE CHESS TURNED KING}

# And you can use those as well:
>> print("\N{SHADOWED WHITE LATIN CROSS}")
✞

```
That could be used to generate `:shadowed_white_latin_cross:`.
The second one "WHITE CHESS TURNED KING" is not displayed on my Windows computer though.
Something like `:white_chess_turned_king:` would not be useful, without the information where it is supported.


Anyway, I doubt I will invest time in this in the near future. I currently work on something else: extracting "diversity" information from the emoji: gender, skin-tone, hair-color

**Comment by novitae** [comment]
> Anyway, I doubt I will invest time in this in the near future. I currently work on something else: extracting "diversity" information from the emoji: gender, skin-tone, hair-color

Hold up ... I just did the exact same thing yesterday (except for hait color), where could I contact you in private ?

**Comment by cvzi** [comment]
cuzi@openmail.cc
