### ISSUE TITLE
Version 2.13.0 breaks pyinstaller

### ISSUE THREAD

**Issue by ethan-wispr** [carpedm20/emoji#304]
I have not looked into it too closely, but it seems like the new json files are not packaged correctly with pyinstaller, at least without additional configuration.

```
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "emoji/unicode_codes/__init__.py", line 103, in <module>
  File "emoji/unicode_codes/__init__.py", line 81, in _load_default_from_json
FileNotFoundError: [Errno 2] No such file or directory: '.../main/_internal/emoji/unicode_codes/emoji.json'
```

Pinning to 2.12.1 resolves the issue.

**Comment by cvzi** [comment]
Could also be that the files are included but they are not in the expected folder? It uses the path of `unicode_codes/__init__.py` and changes the filename to `emoji.json`:
https://github.com/carpedm20/emoji/blob/d34e4bf42ab7fc7284d9a686bb3b97afca3eeba1/emoji/unicode_codes/__init__.py#L81

I don't know what pyinstaller expects to see, so that it correctly includes the files. 
At the moment they are only listed here:
https://github.com/carpedm20/emoji/blob/d34e4bf42ab7fc7284d9a686bb3b97afca3eeba1/pyproject.toml#L50-L51

The pyinstaller docs have these [flags](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-all), maybe those help:
--collect-data MODULENAME, --collect-datas MODULENAME
--collect-binaries MODULENAME
--collect-all MODULENAME

**Comment by cvzi** [comment]
Maybe they need to be listed in
https://github.com/carpedm20/emoji/blob/d34e4bf42ab7fc7284d9a686bb3b97afca3eeba1/MANIFEST.in#L1-L6

**Comment by cvzi** [comment]
This argument solves it: `--collect-data emoji`

Or in the .spec file:
```python
datas = []
datas += collect_data_files('emoji')


a = Analysis(
    ...
    datas=datas,
    ...
)

...
coll = COLLECT(
    ...
    a.datas,
    ...
)

```

**Comment by ethan-wispr** [comment]
That makes sense.  Thank you!
