### ISSUE TITLE
Work backwards: \U0001f382 to :birthday:

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [carpedm20/emoji#34]
Is it possible for this library to work backwards? Example:

`u"\U0001F382"` would change to :birthday:

**Comment by geowurster** [comment]
@The-Penultimate-Defenestrator Yep, it already does that:

```python
>>> import emoji
>>> print(emoji.emojize(u"Happy \U0001F382"))
Happy 🎂
```

Is that not what you had in mind?

**Comment by The-Penultimate-Defenestrator** [comment]
Yes, I wasn't aware it works both ways, and it wasn't in the README. Thanks.

**Comment by geowurster** [comment]
@The-Penultimate-Defenestrator Now that I look at this gain, I led you somewhat astray.  This works, but the `emoji` library isn't actually doing anything - your computer is rendering the unicode code as an emoji icon.  All `emoji.emojize()` does is translate `:emoji:` strings to unicode codes, but in this case the string already contains a unicode code.

For instance:

```python
print(u"\U0001F382")
🎂
```

```console
$ echo "\U0001F382"
🎂
```

**Comment by The-Penultimate-Defenestrator** [comment]
Right. I already have a Unicode string. I need to convert the Unicode string to the emoji code because I am using it with the Discord APi

**Comment by geowurster** [comment]
@The-Penultimate-Defenestrator Ah I get it - I was confused by the actual icon in the ticket header.  If you wrap the text in backticks, like `:birthday:`, then GitHub won't render the string as an icon.

Yes, this is supported:

```python
import emoji

print(emoji.demojize(u"Happy \U0001F382!"))
Happy :birthday_cake:!
```

One note is that the `:birthday:` emoji is actually an alias for `:birthday_cake:`.  You can do `emoji.emojize(":birthday_cake:")` OR `emoji.emojize(":birthday:", use_aliases=True)`, but `emoji.demojize()` does not use aliases.  The reason is that there are multiple aliases mapped to the same unicode code, so its impossible to know which alias the user wants and returning the official string is more likely to work.

**Comment by The-Penultimate-Defenestrator** [comment]
Thanks. Demojize is what I was looking for.
