### ISSUE TITLE
cannot display emoji on linux

### ISSUE THREAD

**Issue by TracyDa** [carpedm20/emoji#39]
just display the unicode  like u5408
but some emoji works

**Comment by geowurster** [comment]
@TracyDa This library only does the conversions from emoji `:name:` to unicode code, so linux can't display all of them because it doesn't icons for all of them.

For instance, my Mac doesn't have an icon for `:satellite:`

```python
import emoji
print(emoji.emojize(':satellite:'))
🛰
```

But GitHub does: :satellite: 

And Slack does too

![slack_and_cannot_display_emoji_on_linux_ _issue__39_ _carpedm20_emoji_and_kwurster_ _kwurster_parsecomm-w-0____ _python_ _80x24](https://cloud.githubusercontent.com/assets/2676083/13355935/d6e9a970-dc70-11e5-8525-c1de6281760c.png)
