### ISSUE TITLE
Docstring formatting

### ISSUE THREAD

**Issue by geowurster** [carpedm20/emoji#9]
@carpedm20 do you have a preference for docstring formatting - looks like you're using RST?  Can you link me to a guide?

**Comment by carpedm20** [comment]
I've never read the formal doc string format but I've read other codes and follow their rule.
I usually read this code https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L386 

Since now I followed sphinx syntax rule, which can be found here : https://pythonhosted.org/an_example_pypi_project/sphinx.html#function-definitions
This format is useful when we consider to make a html documents online.

**Comment by geowurster** [comment]
Thanks, I'll use that.
